server:
  port: 9300
spring:
  datasource:
    url: jdbc:mysql://192.168.1.104:3306/SpringCloud_Sell?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: pw123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  rabbitmq:
    host: 192.168.1.104
    username: admin
    password: pw123456
    port: 5672
    connection-timeout: 10s
  redis:
    port: 6379
    password: pw123456
    host: 192.168.1.104
    database: 1
  cloud:
    stream:
      bindings:
        # queue name 消息分组
        msgInput:
          group: default_order
          content-type: application/json
          destination: default_exchange_order # 指定了消息获取的目的地，对应于MQ就是 exchange
        msgOuput:
          group: default_order
          content-type: application/json
          destination: default_exchange_order # 指定了消息获取的目的地，对应于MQ就是 exchange
        ackMsgInput:
          group: ack_order
          content-type: application/json
          destination: ack_exchange_order # 指定了消息获取的目的地，对应于MQ就是 exchange
        ackMsgOuput:
          group: ack_order
          content-type: application/json
          destination: ack_exchange_order # 指定了消息获取的目的地，对应于MQ就是 exchange  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
feign:
  hystrix:
    enabled: true

opentracing:
  jaeger:
    udp-sender:
      host: 192.168.1.104
      port: 6831
      
logging:
  level:
    org.springframework.cloud: debug

env: dev